export const categories = [
  'Arts',
  'Automobiles',
  'Books',
  'Briefing',
  'Business',
  'Climate',
  'Corrections',
  'Crosswords & Games',
  'Education',
  'En Español',
  'Fashion',
  'Food',
  'Guides',
  'Health',
  'Home & Garden',
  'Home Page',
  'Job Market',
  'Lens',
  'Magazine',
  'Movies',
  'Multimedia/Photos',
  'New York',
  'Obituaries',
  'Opinion',
  'Parenting',
  'Podcasts',
  'Reader Center',
  'Real Estate',
  'Science',
  'Smarter Living',
  'Sports',
  'Style',
  'Sunday Review',
  'T Brand',
  'T Magazine',
  'Technology',
  'The Learning Network',
  'The Upshot',
  'The Weekly',
  'Theater',
  'Times Insider',
  'Today’s Paper',
  'Travel',
  'U.S.',
  'Universal',
  'Video',
  'Well',
  'World',
  'Your Money',
  'Admin',
];
